<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	  <UserSecretsId>7990193b-4119-4a96-8b55-4de4109c6025</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.6.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Areas\Admin\Models\" />
		<Folder Include="Database\Migrations\" />
	</ItemGroup>

</Project>