// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Portfolio.Models;

#nullable disable

namespace Portfolio.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260802215646_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.Models.Entities.duyurular", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("baslik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("gonderitarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("icerik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("kategori")
                        .HasColumnType("text");

                    b.Property<int>("kullanici_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("kullanici_id");

                    b.ToTable("duyurular", "public");
                });

            modelBuilder.Entity("Portfolio.Models.Entities.kullanici", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("cv")
                        .HasColumnType("text");

                    b.Property<string>("durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("foto_url")
                        .HasColumnType("text");

                    b.Property<string>("hakkimda")
                        .HasColumnType("text");

                    b.Property<string>("iletisim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("isim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("kullanici_adi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sifre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("soyisim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("telefonno")
                        .HasColumnType("text");

                    b.Property<string>("unvan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("kullanici", "public");
                });

            modelBuilder.Entity("Portfolio.Models.Entities.kullanici_linkleri", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("baslik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("kullanici_id")
                        .HasColumnType("integer");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("kullanici_id");

                    b.ToTable("kullanici_linkleri", "public");
                });

            modelBuilder.Entity("Portfolio.Models.Entities.navbar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("href")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("kullanici_id")
                        .HasColumnType("integer");

                    b.Property<int>("sira")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("kullanici_id");

                    b.ToTable("navbar", "public");
                });

            modelBuilder.Entity("Portfolio.Models.Entities.projeler", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("kullanici_id")
                        .HasColumnType("integer");

                    b.Property<string>("proje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("kullanici_id");

                    b.ToTable("projeler", "public");
                });

            modelBuilder.Entity("Portfolio.Models.Entities.teklifler", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("eposta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("kullanici_id")
                        .HasColumnType("integer");

                    b.Property<string>("mesaj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("olusturulma_tarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("sirket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ucret")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.HasIndex("kullanici_id");

                    b.ToTable("teklifler", "public");
                });

            modelBuilder.Entity("Portfolio.Models.Entities.yetenek_kategorileri", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("kategori")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("kullanici_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("kullanici_id");

                    b.ToTable("yetenek_kategorileri", "public");
                });

            modelBuilder.Entity("Portfolio.Models.Entities.yetenekler", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("kullanici_id")
                        .HasColumnType("integer");

                    b.Property<string>("yetenek")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("yetenek_kategorileri_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("kullanici_id");

                    b.HasIndex("yetenek_kategorileri_id");

                    b.ToTable("yetenekler", "public");
                });

            modelBuilder.Entity("Portfolio.Models.Entities.duyurular", b =>
                {
                    b.HasOne("Portfolio.Models.Entities.kullanici", "kullanici")
                        .WithMany("duyurular")
                        .HasForeignKey("kullanici_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kullanici");
                });

            modelBuilder.Entity("Portfolio.Models.Entities.kullanici_linkleri", b =>
                {
                    b.HasOne("Portfolio.Models.Entities.kullanici", "kullanici")
                        .WithMany("kullanici_linkleri")
                        .HasForeignKey("kullanici_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kullanici");
                });

            modelBuilder.Entity("Portfolio.Models.Entities.navbar", b =>
                {
                    b.HasOne("Portfolio.Models.Entities.kullanici", "kullanici")
                        .WithMany("navbar")
                        .HasForeignKey("kullanici_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kullanici");
                });

            modelBuilder.Entity("Portfolio.Models.Entities.projeler", b =>
                {
                    b.HasOne("Portfolio.Models.Entities.kullanici", "kullanici")
                        .WithMany("projeler")
                        .HasForeignKey("kullanici_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kullanici");
                });

            modelBuilder.Entity("Portfolio.Models.Entities.teklifler", b =>
                {
                    b.HasOne("Portfolio.Models.Entities.kullanici", "kullanici")
                        .WithMany("teklifler")
                        .HasForeignKey("kullanici_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kullanici");
                });

            modelBuilder.Entity("Portfolio.Models.Entities.yetenek_kategorileri", b =>
                {
                    b.HasOne("Portfolio.Models.Entities.kullanici", "kullanici")
                        .WithMany("yetenek_kategorileri")
                        .HasForeignKey("kullanici_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kullanici");
                });

            modelBuilder.Entity("Portfolio.Models.Entities.yetenekler", b =>
                {
                    b.HasOne("Portfolio.Models.Entities.kullanici", "kullanici")
                        .WithMany("yetenekler")
                        .HasForeignKey("kullanici_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Models.Entities.yetenek_kategorileri", "yetenek_kategori")
                        .WithMany("yetenekler")
                        .HasForeignKey("yetenek_kategorileri_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kullanici");

                    b.Navigation("yetenek_kategori");
                });

            modelBuilder.Entity("Portfolio.Models.Entities.kullanici", b =>
                {
                    b.Navigation("duyurular");

                    b.Navigation("kullanici_linkleri");

                    b.Navigation("navbar");

                    b.Navigation("projeler");

                    b.Navigation("teklifler");

                    b.Navigation("yetenek_kategorileri");

                    b.Navigation("yetenekler");
                });

            modelBuilder.Entity("Portfolio.Models.Entities.yetenek_kategorileri", b =>
                {
                    b.Navigation("yetenekler");
                });
#pragma warning restore 612, 618
        }
    }
}
